In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv(r"..\data\raw\results.csv")

In [5]:
df.isnull().sum()
#Existance of null values in scores
#Matches that are yet to happen
df = df.dropna(subset=["home_score","away_score"])
df

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False
...,...,...,...,...,...,...,...,...,...
49301,2026-06-03,Luxembourg,Italy,0.0,1.0,Friendly,Luxembourg,Luxembourg,False
49302,2026-06-03,Netherlands,Algeria,0.0,1.0,Friendly,Rotterdam,Netherlands,False
49303,2026-06-03,Panama,Dominican Republic,4.0,2.0,Friendly,Panama City,Panama,False
49304,2026-06-03,Poland,Nigeria,2.0,2.0,Friendly,Warsaw,Poland,False
49305,2026-06-03,Philippines,Guam,5.0,1.0,Friendly,Manila,Philippines,False

In [6]:
#Standardize dates
df["date"] = pd.to_datetime(df["date"])
df["year"] = df["date"].dt.year 
df["month"] = df["date"].dt.month 
df

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,year,month
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False,1872,11
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False,1873,3
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False,1874,3
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False,1875,3
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False,1876,3
...,...,...,...,...,...,...,...,...,...,...,...
49301,2026-06-03,Luxembourg,Italy,0.0,1.0,Friendly,Luxembourg,Luxembourg,False,2026,6
49302,2026-06-03,Netherlands,Algeria,0.0,1.0,Friendly,Rotterdam,Netherlands,False,2026,6
49303,2026-06-03,Panama,Dominican Republic,4.0,2.0,Friendly,Panama City,Panama,False,2026,6
49304,2026-06-03,Poland,Nigeria,2.0,2.0,Friendly,Warsaw,Poland,False,2026,6
49305,2026-06-03,Philippines,Guam,5.0,1.0,Friendly,Manila,Philippines,False,2026,6

In [7]:
former = pd.read_csv(r"..\data\raw\former_names.csv")

In [8]:
#Replace older country names with newer ones
name_map = dict(zip(former["former"],former["current"]))

df["home_team"] = df["home_team"].replace(name_map)
df["away_team"] = df["away_team"].replace(name_map)
df

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,year,month
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False,1872,11
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False,1873,3
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False,1874,3
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False,1875,3
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False,1876,3
...,...,...,...,...,...,...,...,...,...,...,...
49301,2026-06-03,Luxembourg,Italy,0.0,1.0,Friendly,Luxembourg,Luxembourg,False,2026,6
49302,2026-06-03,Netherlands,Algeria,0.0,1.0,Friendly,Rotterdam,Netherlands,False,2026,6
49303,2026-06-03,Panama,Dominican Republic,4.0,2.0,Friendly,Panama City,Panama,False,2026,6
49304,2026-06-03,Poland,Nigeria,2.0,2.0,Friendly,Warsaw,Poland,False,2026,6
49305,2026-06-03,Philippines,Guam,5.0,1.0,Friendly,Manila,Philippines,False,2026,6

In [9]:
old_matches = df[df["date"].dt.year>=2000]
df = df[df["date"].dt.year>=2000]
df = df.reset_index(drop=True)
df

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,year,month
0,2000-01-04,Egypt,Togo,2.0,1.0,Friendly,Aswan,Egypt,False,2000,1
1,2000-01-07,Tunisia,Togo,7.0,0.0,Friendly,Tunis,Tunisia,False,2000,1
2,2000-01-08,Trinidad and Tobago,Canada,0.0,0.0,Friendly,Port of Spain,Trinidad and Tobago,False,2000,1
3,2000-01-09,Burkina Faso,Gabon,1.0,1.0,Friendly,Ouagadougou,Burkina Faso,False,2000,1
4,2000-01-09,Guatemala,Armenia,1.0,1.0,Friendly,Los Angeles,United States,True,2000,1
...,...,...,...,...,...,...,...,...,...,...,...
25239,2026-06-03,Luxembourg,Italy,0.0,1.0,Friendly,Luxembourg,Luxembourg,False,2026,6
25240,2026-06-03,Netherlands,Algeria,0.0,1.0,Friendly,Rotterdam,Netherlands,False,2026,6
25241,2026-06-03,Panama,Dominican Republic,4.0,2.0,Friendly,Panama City,Panama,False,2026,6
25242,2026-06-03,Poland,Nigeria,2.0,2.0,Friendly,Warsaw,Poland,False,2026,6
25243,2026-06-03,Philippines,Guam,5.0,1.0,Friendly,Manila,Philippines,False,2026,6

In [10]:
def result(row):
    if row["home_score"] > row["away_score"]:
        return "Home Win"
    elif row["home_score"] < row["away_score"]:
        return "Away Win"
    else:
        return "Draw"

df["result"] = df.apply(result,axis=1)
df.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,year,month,result
0,2000-01-04,Egypt,Togo,2.0,1.0,Friendly,Aswan,Egypt,False,2000,1,Home Win
1,2000-01-07,Tunisia,Togo,7.0,0.0,Friendly,Tunis,Tunisia,False,2000,1,Home Win
2,2000-01-08,Trinidad and Tobago,Canada,0.0,0.0,Friendly,Port of Spain,Trinidad and Tobago,False,2000,1,Draw
3,2000-01-09,Burkina Faso,Gabon,1.0,1.0,Friendly,Ouagadougou,Burkina Faso,False,2000,1,Draw
4,2000-01-09,Guatemala,Armenia,1.0,1.0,Friendly,Los Angeles,United States,True,2000,1,Draw

In [11]:
#Prevent data leakage
df.drop(["home_score","away_score"],axis=1)

,date,home_team,away_team,tournament,city,country,neutral,year,month,result
0,2000-01-04,Egypt,Togo,Friendly,Aswan,Egypt,False,2000,1,Home Win
1,2000-01-07,Tunisia,Togo,Friendly,Tunis,Tunisia,False,2000,1,Home Win
2,2000-01-08,Trinidad and Tobago,Canada,Friendly,Port of Spain,Trinidad and Tobago,False,2000,1,Draw
3,2000-01-09,Burkina Faso,Gabon,Friendly,Ouagadougou,Burkina Faso,False,2000,1,Draw
4,2000-01-09,Guatemala,Armenia,Friendly,Los Angeles,United States,True,2000,1,Draw
...,...,...,...,...,...,...,...,...,...,...
25239,2026-06-03,Luxembourg,Italy,Friendly,Luxembourg,Luxembourg,False,2026,6,Away Win
25240,2026-06-03,Netherlands,Algeria,Friendly,Rotterdam,Netherlands,False,2026,6,Away Win
25241,2026-06-03,Panama,Dominican Republic,Friendly,Panama City,Panama,False,2026,6,Home Win
25242,2026-06-03,Poland,Nigeria,Friendly,Warsaw,Poland,False,2026,6,Draw
25243,2026-06-03,Philippines,Guam,Friendly,Manila,Philippines,False,2026,6,Home Win

In [13]:
df.to_csv(
    "../data/processed/cleaned_matches.csv",
    index=False
)